name = "formal_research"
version = "0.1.0"
defaultTargets = ["FormalResearch"]

[[lean_lib]]
name = "FormalResearch"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "52b284ff128a523eca1f67c68d677861b95cc002"
