import Mathlib
import FormalResearch.QIC.Endpoint14EliminationData0
import FormalResearch.QIC.Endpoint14EliminationData1
import FormalResearch.QIC.Endpoint14EliminationData2
import FormalResearch.QIC.Endpoint14EliminationData3
import FormalResearch.QIC.Endpoint14EliminationData4
import FormalResearch.QIC.Endpoint14EliminationData5

namespace FormalResearch.QIC

open Matrix Equiv.Perm

abbrev EndpointSampleIndex := Fin 29

/-- The 29 distinct nonsingular interpolation values `0,3,4,...,30`. -/
def endpointSample : EndpointSampleIndex → Int :=
  ![0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

def endpointElimPermZeroTo : Fin14 → Fin14 :=
  ![1, 12, 3, 5, 6, 7, 4, 8, 9, 10, 2, 11, 0, 13]
def endpointElimPermZeroInv : Fin14 → Fin14 :=
  ![12, 0, 10, 2, 6, 3, 4, 5, 7, 8, 9, 11, 1, 13]
def endpointElimPermZero : Equiv.Perm Fin14 where
  toFun := endpointElimPermZeroTo
  invFun := endpointElimPermZeroInv
  left_inv := by native_decide
  right_inv := by native_decide

def endpointElimPermGenericTo : Fin14 → Fin14 :=
  ![1, 12, 2, 3, 4, 5, 6, 7, 8, 10, 9, 11, 0, 13]
def endpointElimPermGenericInv : Fin14 → Fin14 :=
  ![12, 0, 2, 3, 4, 5, 6, 7, 8, 10, 9, 11, 1, 13]
def endpointElimPermGeneric : Equiv.Perm Fin14 where
  toFun := endpointElimPermGenericTo
  invFun := endpointElimPermGenericInv
  left_inv := by native_decide
  right_inv := by native_decide

/-- Row permutation used by the exact elimination certificate. -/
def endpointElimPerm (k : EndpointSampleIndex) : Equiv.Perm Fin14 :=
  if k = 0 then endpointElimPermZero else endpointElimPermGeneric

/-- Unit lower-triangular elimination matrices generated by exact rational LU. -/
def endpointElimLower : EndpointSampleIndex → Matrix Fin14 Fin14 ℚ :=
  ![endpointElimLower0,
    endpointElimLower1,
    endpointElimLower2,
    endpointElimLower3,
    endpointElimLower4,
    endpointElimLower5,
    endpointElimLower6,
    endpointElimLower7,
    endpointElimLower8,
    endpointElimLower9,
    endpointElimLower10,
    endpointElimLower11,
    endpointElimLower12,
    endpointElimLower13,
    endpointElimLower14,
    endpointElimLower15,
    endpointElimLower16,
    endpointElimLower17,
    endpointElimLower18,
    endpointElimLower19,
    endpointElimLower20,
    endpointElimLower21,
    endpointElimLower22,
    endpointElimLower23,
    endpointElimLower24,
    endpointElimLower25,
    endpointElimLower26,
    endpointElimLower27,
    endpointElimLower28]

/-- The resulting upper-triangular matrix at sample `k`. -/
def endpointElimUpper (k : EndpointSampleIndex) : Matrix Fin14 Fin14 ℚ :=
  endpointElimLower k * (endpointElimPerm k).permMatrix ℚ *
    endpointReducedAtRat (endpointSample k)

end FormalResearch.QIC
